src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $presentation;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="articles")
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tag;

    /**
     * @ORM\Column(type="integer")
     */
    private $views;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", orphanRemoval=true)
     */
    private $comments;


    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->tag = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tag->removeElement($tag);

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /*public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }*/

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Form\ArticleType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * Class ArticleController
 * @package App\Controller
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/article", name="article_index", methods={"GET"})
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $em = $this->getDoctrine()->getManager();
        //$em= $this->entityManager->createQuery();
        $dql = "SELECT p FROM App:Article p ORDER BY p.created_at DESC";
        $donnees = $em->createQuery($dql);

        $articles = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            5 // Nombre de résultats par page
        );

        return $this->render('article/index.html.twig', [
            //'articles' => $articleRepository->findAll(),
            'articles' => $articles,
            'current_menu' => 'Blog',
        ]);
    }

    /**
     * @Route("/admin/article", name="article_admin_index", methods={"GET"})
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function indexAdmin(Request $request, PaginatorInterface $paginator): Response
    {
        $em = $this->getDoctrine()->getManager();
        $dql = "SELECT p FROM App:Article p ORDER BY p.created_at DESC";
        $donnees = $em->createQuery($dql);

        $articles = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            5 // Nombre de résultats par page
        );

        return $this->render('article/index.admin.html.twig', [
            //'articles' => $articleRepository->findAll(),
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/admin/article/new", name="article_new", methods={"GET","POST"})
     * @param Request $request
     * @param TranslatorInterface $translator
     * @return Response
     */
    public function new(Request $request, TranslatorInterface $translator): Response
    {
        $article = new Article();

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Upload image
            $uploadedFile = $form['image']->getData();

            if ($uploadedFile) {
                $destination = $this->getParameter("articles_images_directory");

                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();

                $uploadedFile->move(
                    $destination,
                    $newFilename
                );
                $article->setImage($newFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();

            // Article creation date and time
            $article->setCreatedAt(new \DateTimeImmutable());

            // Article author (the one who's connected)
            $article->setAuthor($this->getUser());

            // Set views number to 1
            $article->setViews('1');

            $entityManager->persist($article);
            $entityManager->flush();

            $message = $translator->trans('L\'article a été créé avec succès.');
            $this->addFlash('message', $message);

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/article/{slug}", name="article_show", methods={"GET","POST"})
     * @param Article $article
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param MailerInterface $mailer
     * @return Response
     */
    public function show(Article $article, Request $request, EntityManagerInterface $manager, MailerInterface $mailer): Response
    {
        // Set +1 view for each visit
        $read = $article->getViews() +1;
        $article->setViews($read);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($article);
        $entityManager->flush();

        // Comments
        $comment = new Comment;
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);

        // Form
        if($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setCreatedAt(new \DateTimeImmutable());
            $comment->setArticle($article);

            // Fetch parentid content
            $parentid = $commentForm->get("parentid")->getData();

            $em = $this->getDoctrine()->getManager();

            // Fetch corresponding comment
            if ($parentid != null) {
                $parent = $em->getRepository(Comment::class)->find(($parentid));
            }

            // Define parent
            $comment->setParent($parent ?? null);

            $em->persist($comment);
            $em->flush();

            $this->addFlash('success', 'Merci pour votre commentaire.');
            return $this->redirectToRoute('article_show', ['slug' => $article->getSlug()]);
        }

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'commentForm' => $commentForm->createView()
        ]);
    }

    /**
     * @Route("/admin/article/{slug}/edit", name="article_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Article $article
     * @param TranslatorInterface $translator
     * @return Response
     */
    public function edit(Request $request, Article $article, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Upload image
            $uploadedFile = $form['image']->getData();

            if ($uploadedFile) {
                $image = $article->getImage();
                if($image) {
                    $nomImage = $this->getParameter("articles_images_directory") . '/' . $image;
                    if(file_exists($nomImage)) {
                        unlink($nomImage);
                    }
                }

                $destination = $this->getParameter("articles_images_directory");

                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();

                $uploadedFile->move(
                    $destination,
                    $newFilename
                );
                $article->setImage($newFilename);
            }

            // Modification date and time
            $article->setUpdatedAt(new \DateTimeImmutable());

            $this->getDoctrine()->getManager()->flush();

            $message = $translator->trans('Le message a été modifié avec succès.');
            $this->addFlash('message', $message);

            return $this->redirectToRoute('article_admin_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/article/{slug}/delimage", name="article_delete_image", methods={"GET"})
     * @param Request $request
     * @param Article $article
     * @param TranslatorInterface $translator
     * @return Response
     */
    public function deleteImage(Request $request, Article $article, TranslatorInterface $translator): Response
    {
        // Delete article's image in folder
        $image = $article->getImage();
        if($image) {
            $nomImage = $this->getParameter("articles_images_directory") . '/' . $image;
            if(file_exists($nomImage)) {
                unlink($nomImage);
            }
        }

        // Set image to "nothing" in DB
        $article->setImage('');
        $this->getDoctrine()->getManager()->flush();

        // Redirect to edit page
        $message = $translator->trans('L\'image de l\'article a été supprimée avec succès.');
        $this->addFlash('message', $message);

        return $this->redirectToRoute('article_edit', ['slug' => $article->getSlug()]);
    }

    /**
     * @Route("/admin/article/{slug}", name="article_delete", methods={"POST"})
     * @param Request $request
     * @param Article $article
     * @param TranslatorInterface $translator
     * @return Response
     */
    public function delete(Request $request, Article $article, TranslatorInterface $translator): Response
    {
        // Delete image
        $image = $article->getImage();

        if($image) {
            $nomImage = $this->getParameter("articles_images_directory") . '/' . $image;
            if(file_exists($nomImage)) {
                unlink($nomImage);
            }
        }

        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'slug': article.slug}) }}" onsubmit="return confirm('Etes-vous certain(e) de vouloir supprimer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-sm btn-danger">{% trans %}Supprimer{% endtrans %}</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {#{ form_widget(form) }#}
    {{ form_row(form.title) }}
    <div class="my-3">
        {{ form_row(form.presentation) }}
    </div>
    <div class="my-3">
        {{ form_row(form.content) }}
    </div>

    {% if app.request.get('_route') == 'article_edit' %}
        {% if article.image is not empty %}
        {% trans %}Image actuelle{% endtrans %} : {{ article.image }}<br>
            <img src="{{ asset('uploads/images/articles/' ~ article.image) }}" alt="{{ article.title }}" class="img-fluid mb-3 article-show-image">
            <p>
                <a href="{{ path('article_delete_image', {'slug': article.slug}) }}" class="btn btn-sm btn-danger">{% trans %}Supprimer l'image{% endtrans %}</a>
            </p>
        {% else %}
            <div class="text-white bg-danger p-2 mb-2 text-center">
                <i class="bi bi-exclamation-lg"></i> {% trans %}Il n'y a aucune image pour cet article. Veuillez en sélectionner une.{% endtrans %}
            </div>
        {% endif %}
    {% endif %}
    
    {{ form_row(form.image) }}
    {{ form_row(form.category) }}
    {{ form_row(form.tag) }}

    <div class="mt-4">
        <button class="btn btn-sm btn-success">{{ button_label|default('Créer') }}</button> 
        <button class="btn btn-sm btn-secondary" type="reset">{% trans %}Annuler{% endtrans %}</button> 
        <a class="btn btn-sm btn-primary" href="{{ path('article_admin_index') }}">{% trans %}Liste des articles{% endtrans %}</a>
    </div>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - {% trans %}Modifier l'article{% endtrans %}{% endblock %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}


{% block body %}

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>{% trans %}Modifier l'article{% endtrans %}</h2>

        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('admin') }}">Admin index</a></li>
                <li class="breadcrumb-item active" aria-current="page">Modifier l'article</li>
            </ol>
        </nav>
    </div>

    {{ include('article/_form.html.twig', {'button_label': 'Modifier'}) }}

{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
        $(function(){
            $('.select-tags').select2({
                tags: true,
                tokenSeparators: [',', ' ']
            }).on('change', function(e){
                let label = $(this).find("[data-select2-tag=true]")
                if(label.length && $.inArray(label.val(), $(this).val() !== -1)){
                    $.ajax({
                        url: "/admin/tag/new/ajax/" + label.val(),
                        type: "POST"
                    }).done(function(data){
                        label.replaceWith(`<option selected value="${data.id}">${label.val()}</option>`);
                    })
                }
            });
        })
    </script>
{% endblock %}

templates/article/index.admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - {% trans %}Liste des articles{% endtrans %}{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>{% trans %}Liste des articles{% endtrans %}</h2>

        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('admin') }}">{% trans %}Admin index{% endtrans %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans %}Liste des articles{% endtrans %}</li>
            </ol>
        </nav>
    </div>

    
    <table class="table table-hover">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(articles, 'Id', 'p.id') }}</th>
                <th>{{ knp_pagination_sortable(articles, 'Titre'|trans({}, 'messages'), 'p.title') }}</th>
                <th width="15%">{{ knp_pagination_sortable(articles, 'Posté le'|trans({}, 'messages'), 'p.created_at') }}</th>
                <th width="15%">{{ knp_pagination_sortable(articles, 'Maj le'|trans({}, 'messages'), 'p.updated_at') }}</th>
                <th width="11%"></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.createdAt|format_datetime('medium', 'short') }}</td>
                <td>
                    {% if article.updatedAt %}
                        {{ article.updatedAt|format_datetime('medium', 'short') }}
                    {% endif %}
                </td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('article_show', {'slug': article.slug}) }}">{% trans %}Voir{% endtrans %}</a>
                    <a class="btn btn-sm btn-warning" href="{{ path('article_edit', {'slug': article.slug}) }}">{% trans %}Modifier{% endtrans %}</a>
                </td>
                <td>
                    {{ include('article/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">{% trans %}Il n'y a aucun enregistrement{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="pagination justify-content-center px-2 mt-5">
        {{ knp_pagination_render(articles) }}
    </div>

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - {% trans %}Tous les articles{% endtrans %}{% endblock %}

{% block body %}
<h2 class="border-bottom mb-4 text-primary">{% trans %}Tous les articles{% endtrans %}</h2>

<div class="row">

    <div class="col-9 pe-4">
        {% for article in articles %}
            <a href="{{ path('article_show', {'slug': article.slug}) }}" class="text-decoration-none text-dark h4">{{ article.title }}</a>
            <p class="mt-1 fst-italic">
                {{ article.presentation }}
            </p>
            <p>
                <img src="{{ asset('uploads/images/articles/' ~ article.image) }}" class="img-fluid img-thumbnail float-end ms-3 mt-1" alt="{{ article.title }}">
                {{ article.content|slice(0,250)|raw }}...
            </p>
            <a href="{{ path('article_show', {'slug': article.slug}) }}" class="text-decoration-none">
                <span>{% trans %}Lire la suite{% endtrans %} &#8594;</span>
            </a>
            <hr>
        {% endfor %}
    </div>
    <div class="col-3 shadow pt-3">
        {% block sidebar %}
            {{ sidebar() }}
        {% endblock %}
    </div>

    <div class="col-9 pagination justify-content-center px-2 mt-3 mb-5">
        {{ knp_pagination_render(articles) }}
    </div>

</div>

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - {{ article.title }}{% endblock %}

{% block body %}
<div class="row">
    <div class="col">
        <p>
            {% for cat in article.category %}
            <a href="{{ path('category_show', {'slug': cat.slug}) }}"
                class="text-decoration-none font-monospace text-dark me-1 lead">
                {{ cat.title }}
            </a>
            {% endfor %}
            <br>
            {% for tag in article.tag %}
            <a href="{{ path('tag_show', {'slug': tag.slug}) }}" class="text-decoration-none text-dark">
                <span class="article-tag">{{ tag.title }}</span>
            </a>
            {% endfor %}
        </p>
        <h1>{{ article.title }}</h1>
        <p class="lead">
            {{ article.presentation }}
        </p>

        {% if is_granted('ROLE_ADMIN') %}
        <table>
            <tr>
                <td>
                    <a class="btn btn-sm btn-warning text-dark"
                        href="{{ path('article_edit', {'slug': article.slug}) }}">{% trans %}Modifier{% endtrans %}</a>
                </td>
                <td>
                    {{ include('article/_delete_form.html.twig') }}
                </td>
            </tr>
        </table>
        {% endif %}

        <div class="row">
            <div class="col-9 pe-4">
                <img src="{{ asset('uploads/images/articles/' ~ article.image) }}"
                    class="img-fluid float-start me-3 mt-2" alt="{{ article.title }}">
                {{ article.content|raw }}
                <div class="bg-light rounded p-2">
                    <i class="fas fa-calendar-alt"></i>
                    {{ article.createdAt|format_datetime('medium', 'short') }}
                    {% if article.updatedAt %}
                    &nbsp;|&nbsp;<i class="fas fa-undo"></i>
                    {{ article.updatedAt|format_datetime('medium', 'short') }}
                    {% endif %}
                    &nbsp;|&nbsp;<i class="fas fa-user-tie"></i> {{ article.author.prenom }} {{ article.author.nom }}
                </div>
            </div>
            <div class="col shadow pt-3">
                {% block sidebar %}
                {{ sidebar() }}
                {% endblock %}
            </div>
        </div>

    </div>
</div>

<!-- Commentaires -->
<div id="comments" class="row mt-3">
    <div class="col-9">
        <h3 class="border-bottom">{% trans %}Liste des commentaires{% endtrans %}
            {% if article.comments|length == 0 %}
                <span class="fs-6">({% trans %}Il n'y a aucun commentaire{% endtrans %})</span>
            {% else %}
                ({{ article.comments|length }})
            {% endif %}
        </h3>

        <!-- Comments -->
        {% for comment in article.comments %}

            {% if comment.parent == null %}

                {% if comment.active == true %}
                <div class="px-3 pt-3">
                    <h5>
                        {{ comment.nickname }}
                        <a href="#reply-comment" data-reply data-id={{ comment.id }} class="reply text-decoration-none">
                            <i class="fas fa-reply"></i> {% trans %}Répondre{% endtrans %}
                        </a>
                    </h5>
                    <time datetime="{{ comment.createdAt|format_datetime('medium', 'short') }}">
                        {{ comment.createdAt|format_datetime('medium', 'short') }}
                    </time>
                    <p>
                        {{ comment.content|raw }}
                    </p>
                    <p>
                        {% if app.user %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <table>
                                    <tr>
                                        <td>
                                            <a class="btn btn-sm btn-warning" href="{{ path('comment_edit', {'id': comment.id}) }}">modifier</a>
                                        </td>
                                        <td>
                                            {{ include('comment/_delete_form.html.twig') }}
                                        </td>
                                    </tr>
                                </table>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                {% endif %}

                {# show reply #}
                {% for reply in comment.replies %}

                    {% if reply.active == true %}
                    <div class="px-3 pt-3 comment-reply">
                        <h5>
                            {{ reply.nickname }}
                        </h5>
                        <div>
                            <time datetime="{{ reply.createdAt|format_datetime('medium', 'short') }}">
                                {{ reply.createdAt|format_datetime('medium', 'short') }}
                            </time>
                        </div>
                        <p>
                            {{ reply.content|raw }}
                        </p>
                        <p>
                            {% if app.user %}
                                {% if is_granted('ROLE_ADMIN') %}
                                    <table>
                                        <tr>
                                            <td>
                                                <!-- Pas bon - mauvais ID de comment -->
                                                <a class="btn btn-sm btn-warning" href="{{ path('comment_edit', {'id': reply.id}) }}">modifier</a>
                                            </td>
                                            <td>
                                                {{ include('comment/_delete_form.html.twig') }}
                                            </td>
                                        </tr>
                                    </table>
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                    {% endif %}
                {% endfor %}

            {% endif %}

        {% endfor %}

    </div>
</div>

<div class="row mt-5">
    <div class="col-9">
        <h3 class="border-bottom">{% trans %}Ajouter un commentaire{% endtrans %}</h3>
        {{ form_start(commentForm) }}
        {{ form_row(commentForm.nickname) }}
        {{ form_row(commentForm.content) }}
        <table class="mb-3">
            <tr>
                <td width="2%">
                    {{ form_row(commentForm.rgpd, {'label': false}) }}
                </td>
                <td class="small">
                    {% trans %}J'accepte que mes informations soient stockées en base de données. J'ai bien noté qu'en aucun cas ces données ne seront cédées à des tiers.{% endtrans %}
                </td>
            </tr>
        </table>
        {% trans %}Recopiez le code antispam{% endtrans %} :<br>
        {{ form_row(commentForm.captcha, {'label': false}) }}
        <div class="mt-2">
            <button class="btn btn-sm btn-success">{% trans %}Envoyer le message{% endtrans %}</button>
            <button class="btn btn-sm btn-secondary" type="reset">{% trans %}Annuler{% endtrans %}</button>
        </div>
        {{ form_end(commentForm) }}
    </div>
</div>

{% endblock %}

{% block javascripts %}
<script>
    window.onload = () => {
        // Listener event on each Reply button
        document.querySelectorAll("[data-reply]").forEach(element => {
            element.addEventListener("click", function () {
                document.querySelector("#comment_parentid").value = this.dataset.id;
            });
        });
    }
</script>
{% endblock %}